name: Periodic Update Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  submit-pr:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install ${{ matrix.collection-name }}
        run: |
          python -m pip install --upgrade pip build
          python -m pip install pandas

      - name: Update ONI Table
        run: |
          python process_oni.py

      - name: Update ML Table
        run: |
          python process_nino_ml.py

      - name: Submit PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Updating ${{ matrix.collection-name }} metadata
          branch: update-${{ matrix.collection-name }}-metadata
          delete-branch: true
          title: Update ${{ matrix.collection-name }} metadata with new releases
          body: |
            Automated PR created to update ${{ matrix.collection-name }} metadata.
            Feel free to make any necessary changes to this PR before merging.
          labels: |
            update metadata
            automated pr
